config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :registers

  
  root to: "welcome#index"
  get "inicio", to: "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/register.rb
class Register < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end
        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
         
    end
    
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: %i[ show edit update destroy ]

  # GET /registers or /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1 or /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers or /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to register_url(@register), notice: "Register was successfully created." }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1 or /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to register_url(@register), notice: "Register was successfully updated." }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1 or /registers/1.json
  def destroy
    @register.destroy

    respond_to do |format|
      format.html { redirect_to registers_url, notice: "Register was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def register_params
      params.require(:register).permit(:name, :number, :city, :cpf)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:teste_C] = "William"
    session[:teste_S] = "Mombach"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoFinal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
  <footer class="page-footer">
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">Defesa Civil</h5>
      <p class="grey-text text-lighten-4">Você em Alerta</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Links</h5>
      <ul>
        <li><a class="grey-text text-lighten-3" href="/registers">Registros</a></li>

      </ul>
    </div>
  </div>
</div>
</footer>

    <%= yield %>

  <style>
  .page-footer {
    background-color: #5cacc4;
}
.grey-text text-lighten-3 {
    color: #000000;
}
  </style>

  </body>
</html>

app/views/registers/_form.html.erb
<%= form_with(model: register, local: true) do |form| %>
  <% if register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>  

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editando Registro</h1>

<%= render 'form', register: @register %>

<%= link_to 'Mostrar', @register %> |
<%= link_to 'Voltar', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registros</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Numero</th>
      <th>Cidade</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.name %></td>
        <td><%= register.number %></td>
        <td><%= register.city %></td>
        <td><%= register.cpf %></td>
        <td><%= link_to 'Mostrar', register %></td>
        <td><%= link_to 'Editar', edit_register_path(register) %></td>
        <td><%= link_to 'Apagar', register, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo registro', new_register_path %>

app/views/registers/new.html.erb
<h1>Novo Registro</h1>

<%= render 'form', register: @register %>

<%= link_to 'Voltar', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @register.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @register.number %>
</p>

<p>
  <strong>City:</strong>
  <%= @register.city %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @register.cpf %>
</p>

<%= link_to 'Editar', edit_register_path(@register) %> |
<%= link_to 'Voltar', registers_path %>

app/views/welcome/index.html.erb
<table class="highlight responsive-table
striped">


<p><%=link_to 'English', '/?locale=en' %> </p>

<p><%=link_to 'Portugues', root_path(locale:"pt-BR") %> </p>

<% alert_msg = Time.now.hour < 12 ? "Bom dia" : Time.now < 18 ? "Boa Tarde" : "Boa Noite" %>

<script>

$.notify("<%= alert_msg %>", "success");
console.log("teste")

</script>